<?php

/**
 * Implements hook_node_view().
 */
function demo2_node_view($node, $view_mode = 'full') {
  //only when looking at the full version, NOT the teaser
  if ($view_mode == 'full') {

    // Everytime a node is viewed, increment the node_views count
    // in the user's session by one and include the result in the node content

    //make sure there is a record in the session
    if (empty($_SESSION['node_views'][$node->nid])) {
      $_SESSION['node_views'][$node->nid] = 0;
    }
    
    #krumo('Before: '.$_SESSION['node_views'][$node->nid]);

    //add another to the session
    $_SESSION['node_views'][$node->nid]++;

    #krumo('After: '.$_SESSION['node_views'][$node->nid]);


    // Set up an array of placeholders to pass to t().
    $t_args = array(
      '%num' => $_SESSION['node_views'][$node->nid],
    );

    $node->content['node_views'] = array(
      '#markup' => t('You have viewed this page %num times.', $t_args),
      '#weight' => 10,
    );
  }
}
