<?php
// $Id$

/**
 * @file
 * Use this module to learn about jQuery.
 */

/**
 * Implementation of hook_init().
 */
function blockaway_init() {
  theme('blockaway_javascript');
}

/**
 * Implementation of hook_theme().
 * Registers our theme function.
 */
function blockaway_theme() {
  return array(
    'blockaway_javascript' => array(
      'arguments' => array(),
    ),
  );
}

/**
 * Theme function that just makes sure our JavaScript file
 * gets included.
 */
function theme_blockaway_javascript() {
  drupal_add_js(drupal_get_path('module', 'blockaway') .'/blockaway.js');
}